[package]
name = "cloud-artefact"
edition = "2021"
version = "0.1.0"

[workspace]

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = "1.0.217"
serde_derive = "1.0.217"
serde_json = "1.0.135"
wasmcloud-component = "0.2.0"
wit-bindgen = "0.36.0"
