[package]
name = "http-hello-world"
edition = "2021"
version = "0.1.0"

[workspace]

[lib]
crate-type = ["cdylib"]

[dependencies]
base64 = "0.22.1"
data-encoding = "2.6.0"
hmac = "0.12.1"
sha2 = "0.10.8"
wasmcloud-component = "0.2.0"
wit-bindgen = "0.36.0"
